language: node_js
node_js:
  - 18
  - lts/* # safety net; don't remove
  - node # safety net; don't remove
script:
  - npm run build
  - npm run test
  - npm run cover
  - codecov
branches:
  only:
    - master
